final project/ElecTienda/ElECTIENDA.MVC/Controllers/MemberShipController.cs
using Microsoft.AspNetCore.Mvc;
using ELECTIENDA.Repository;
using ELECTIENDA.ViewModel;

namespace ElECTIENDA.MVC.Controllers
{
    public class MemberShipController : Controller
    {
        private readonly MembershipRepository MembershipRepo;
        
        private readonly UnitOfWork unitOfWork;
        public MemberShipController(MembershipRepository _MemberShipRepo, UnitOfWork _UnitOfWork, CategoryRepository _CatRepo)
        {
            MembershipRepo = _MemberShipRepo;
            unitOfWork = _UnitOfWork;
            
        }
        public IActionResult AdminGet(string name = "",
             string orderby = "Id", bool isAscending = false,
             int pageIndex = 1, int pageSize = 20)
        {


            var result = MembershipRepo.Get(name, orderby, isAscending, pageIndex,
                             pageSize);
            return View(result);
        }

        [HttpGet]
        public IActionResult Add()
        {
           
            return View();
        }
        [HttpPost]
        public IActionResult Add(MemberShipEditViewModel model)
        {
            MembershipRepo.Add(model);
            unitOfWork.Save();

            return RedirectToAction("AdminGet");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            MemberShipEditViewModel? data = MembershipRepo.GetByID(id);
            
            return View(data);
        }

        [HttpPost]
        public IActionResult Edit(MemberShipEditViewModel model)
        {


            MembershipRepo.Update(model);
            unitOfWork.Save();
            return RedirectToAction("AdminGet");


        }

        public IActionResult Remove(int id)
        {
            MembershipRepo.SoftDeleted(id);
            unitOfWork.Save();
            return RedirectToAction("AdminGet");

        }

    }
}

final project/ElecTienda/ElECTIENDA.MVC/Views/MemberShip/Add.cshtml
@using ELECTIENDA.ViewModel;
@model MemberShipEditViewModel;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers
@{
    Layout = "_LayoutAdminPanelComponents";
}

<html>
    <head>
        <link rel="stylesheet" href="~/Content/lib/twitter-bootstrap/css/bootstrap.css"/>
    </head>
    <body>
        <section></section>
        <main>
            <form method="post" asp-action="Add" asp-controller="MemberShip">
  <div class="mb-3">
      <label asp-for="Role" class="form-label">Type</label>
    <input asp-for="Role" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3">
    <label asp-for="DurartionTime" class="form-label">Duration</label>
    <input asp-for="DurartionTime" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3">
    <label asp-for="Price" class="form-label">Price</label>
    <input asp-for="Price" class="form-control" id="exampleInputPassword1">
  </div>
     
  <button type="submit" class="btn btn-primary">Add</button>

</form>


        </main>
       <section></section>
       </body>
</html>

final project/ElecTienda/ElECTIENDA.MVC/Views/MemberShip/AdminGet.cshtml
@model IPagedList<MemberShipViewModel>


@{
    Layout = "_LayoutAdminPanelComponents";
}

<br />
<br />
<a class="btn btn-primary" asp-action="Add" asp-controller="MemberShip" role="button">Add</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Type</th>
            <th scope="col">Duration</th>
            <th scope="col">Price</th>


            <th scope="col">Delete</th>
            <th scope="col">Update</th>

        </tr>
    </thead>
    <tbody>
        @foreach (MemberShipViewModel s in Model)
        {
            <tr>
                @*      <th scope="row">@s.ID</th>
            *@
                <td>@s.Role</td>
                <td>@s.DurartionTime</td>
                <td>@s.Price</td>
                <td><button class="btn btn-danger"><a asp-action="Remove" asp-controller="MemberShip" asp-route-id="@s.ID"> Delete</a></button></td>
                <td><button class="btn btn-dark"><a asp-action="Edit" asp-controller="MemberShip" asp-route-id="@s.ID"> Edit</a></button></td>
            </tr>
        }
    </tbody>
</table>

<br />
<br />

<div class="" style="margin-left:30%">
    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Search", new { pageIndex = page }),
    new X.PagedList.Web.Common.PagedListRenderOptions
    {
    DisplayItemSliceAndTotal = true,
    ContainerDivClasses = new[] { "navigation" },
    LiElementClasses = new[] { "page-item" },
    PageClasses = new[] { "page-link" },
    })
</div>



<script>
    $(document).ready(function() {
        $('ul.pagination > li.disabled > a').addClass('page-link');
    });
</script>

final project/ElecTienda/ElECTIENDA.MVC/Views/MemberShip/Edit.cshtml
@using ELECTIENDA.ViewModel
@model MemberShipEditViewModel 

@{
    Layout = "_LayoutAdminPanelComponents";
} 

<form method="post" asp-action="Edit" asp-controller="membership"> 
  
    <div>
        <input asp-for="ID" type="hidden" hidden/>
    </div>
@*    <div>
     <label asp-for="ProviderId"></label>
     <input asp-for="ProviderId"/>
 
 </div>*@
    
     
    <div> 
        <label asp-for="Role"></label> 
        <input asp-for="Role" /> 
    </div> 
    <div> 
        <label asp-for="DurartionTime"></label> 
        <input asp-for="DurartionTime" /> 
    </div> 
    <div> 
        <label asp-for="Price"></label> 
        <input asp-for="Price" /> 
    </div>
<div>
        <input type="submit" class="form-control" value="Edit" /> 
    </div> 
 
</form>