final project/ElecTienda/ElECTIENDA.MVC/Controllers/RateController.cs
using Microsoft.AspNetCore.Mvc;
using ELECTIENDA.Repository;
using FirstLyer.Model;

using ELECTIENDA.ViewModel;

namespace ELECTIENDA.MVC
{
    public class RateController : Controller
    {
        private readonly RateRepository RateRepo;
        private readonly UnitOfWork UnitOfWork;
        public RateController(RateRepository _RateRepo , UnitOfWork _UnitOfWork)
        {
            RateRepo = _RateRepo;
            UnitOfWork = _UnitOfWork;
        }
        public IActionResult Get(decimal? rate = null, string ProductName = "",
                    string orderBy = "ID", bool isAscending = false, int pageIndex = 1,
                    int pageSize = 20)
        {
            
            //PaginingViewModel<List<RateViewModel>> result
            //    = RateRepo.Get(rate, ProductName, orderBy, isAscending, pageIndex,
            //                 pageSize);
            //return View(result.Data);

           var result
              = RateRepo.Search2(rate, ProductName, orderBy, isAscending, pageIndex,
                           pageSize);
            return View(result);

        }
        public IActionResult GetByResult(int Id) { 
        var result = RateRepo.GetByID(Id);
            return View(result);
        }

        public IActionResult RateAccepted(int id)
        {
            RateRepo.RateAccepted(id);
            UnitOfWork.Save();
            return RedirectToAction("Get");

        }

        public IActionResult RateRejected(int id)
        {
            RateRepo.RateRejected(id);
            UnitOfWork.Save();
            return RedirectToAction("Get");

        }



    }
}

final project/ElecTienda/ElECTIENDA.MVC/Views/Rate/Get.cshtml
@model IPagedList<RateViewModel>

     
@{
    Layout = "_LayoutAdminPanelComponents";
}

<br/>
<br/>

 <table class="table">
  <thead>
    <tr>
@*      <th scope="col">#</th>
*@      <th scope="col">rate</th>
      <th scope="col">review</th>
      <th scope="col">User Name</th>
       <th scope="col">product Name</th>
       <th scope="col">Status</th>
       <th scope="col"></th>
 <th scope="col"></th>      
    </tr>
  </thead>
  <tbody>
    @foreach(RateViewModel cat in Model)
     { <tr>
@*      <th scope="row">@cat.ID</th>
*@      
      <td>@cat.Rating</td>
      <td>@cat.Review</td>
      @foreach(var str in cat.ProductName)
                        {
                            <td> str</td>
                        }
    

      @foreach(var str in cat.UserName)
                        {
                            <td> str</td>
                        }
      <td> @cat.Statues</td>
       <td> <button> <a asp-action="RateAccepted" asp-controller="Rate" asp-route-ID="@cat.ID">Accepted</a> </button></td>
   <td> <button><a asp-action="RateRejected" asp-controller="Rate"  asp-route-ID="@cat.ID">Cancel</a> </button></td>

    </tr>
    }
 </tbody>
</table>
   
<br /> 
<br /> 

<div cite="" style="margin-left:30%">
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("Search", new { pageIndex = page }),
        new X.PagedList.Web.Common.PagedListRenderOptions
        {
        DisplayItemSliceAndTotal = true,
        ContainerDivClasses = new[] { "navigation" },
        LiElementClasses = new[] { "page-item" },
        PageClasses = new[] { "page-link" },
        })
    </div>



     <script>
        $(document).ready(function() {
            $('ul.pagination > li.disabled > a').addClass('page-link');
        });
    </script>